/**
 * Compatibility Service
 * Handles part_spa_compatibility (SOURCE OF TRUTH) and Compatibility Groups (Comps)
 */

import { db } from '../config/database';
import {
  PartSpaCompatibility,
  CreateCompatibilityInput,
  CompatibilityGroup,
  CreateCompInput,
  UpdateCompInput,
  CompSpa,
  CompNearMatch,
  DbPartSpaCompatibility,
  DbCompatibilityGroup,
  CompatibilityStatus,
  PaginationParams,
} from '../types/uhtd.types';
import { logAudit } from './audit.service';

// =============================================================================
// Utility Functions
// =============================================================================

function mapCompatibilityFromDb(
  row: DbPartSpaCompatibility & {
    part_name?: string;
    part_number?: string;
    spa_model_name?: string;
    spa_year?: number;
    brand_name?: string;
  }
): PartSpaCompatibility {
  return {
    partId: row.part_id,
    spaModelId: row.spa_model_id,
    status: row.status,
    fitNotes: row.fit_notes,
    quantityRequired: row.quantity_required,
    position: row.position,
    source: row.source,
    addedBy: row.added_by,
    addedAt: row.added_at,
    reviewedBy: row.reviewed_by,
    reviewedAt: row.reviewed_at,
    partName: row.part_name,
    partNumber: row.part_number,
    spaModelName: row.spa_model_name,
    spaYear: row.spa_year,
    brandName: row.brand_name,
  };
}

function mapCompFromDb(
  row: DbCompatibilityGroup & {
    spa_count?: string;
    part_count?: string;
    source_category_name?: string;
  }
): CompatibilityGroup {
  return {
    id: row.id,
    name: row.name,
    description: row.description,
    autoGenerated: row.auto_generated,
    sourceCategoryId: row.source_category_id,
    createdBy: row.created_by,
    deletedAt: row.deleted_at,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    spaCount: row.spa_count ? parseInt(row.spa_count, 10) : undefined,
    partCount: row.part_count ? parseInt(row.part_count, 10) : undefined,
    sourceCategoryName: row.source_category_name,
  };
}

// =============================================================================
// Part-Spa Compatibility (SOURCE OF TRUTH)
// =============================================================================

export async function getCompatibilitiesForPart(
  partId: string,
  status?: CompatibilityStatus
): Promise<PartSpaCompatibility[]> {
  let query = db('part_spa_compatibility')
    .select(
      'part_spa_compatibility.*',
      'scdb_spa_models.name as spa_model_name',
      'scdb_spa_models.year as spa_year',
      'scdb_brands.name as brand_name'
    )
    .leftJoin('scdb_spa_models', 'part_spa_compatibility.spa_model_id', 'scdb_spa_models.id')
    .leftJoin('scdb_brands', 'scdb_spa_models.brand_id', 'scdb_brands.id')
    .where('part_spa_compatibility.part_id', partId);

  if (status) {
    query = query.where('part_spa_compatibility.status', status);
  }

  const rows = await query
    .orderBy('scdb_brands.name')
    .orderBy('scdb_spa_models.name')
    .orderBy('scdb_spa_models.year', 'desc');

  return rows.map(mapCompatibilityFromDb);
}

export async function getCompatibilitiesForSpa(
  spaModelId: string,
  status?: CompatibilityStatus
): Promise<PartSpaCompatibility[]> {
  let query = db('part_spa_compatibility')
    .select(
      'part_spa_compatibility.*',
      'pcdb_parts.name as part_name',
      'pcdb_parts.part_number'
    )
    .leftJoin('pcdb_parts', 'part_spa_compatibility.part_id', 'pcdb_parts.id')
    .where('part_spa_compatibility.spa_model_id', spaModelId);

  if (status) {
    query = query.where('part_spa_compatibility.status', status);
  }

  const rows = await query.orderBy('pcdb_parts.name');
  return rows.map(mapCompatibilityFromDb);
}

export async function getCompatibility(
  partId: string,
  spaModelId: string
): Promise<PartSpaCompatibility | null> {
  const row = await db('part_spa_compatibility')
    .select('*')
    .where({ part_id: partId, spa_model_id: spaModelId })
    .first();
  return row ? mapCompatibilityFromDb(row) : null;
}

export async function createCompatibility(
  input: CreateCompatibilityInput,
  userId?: string
): Promise<PartSpaCompatibility> {
  const [row] = await db('part_spa_compatibility')
    .insert({
      part_id: input.partId,
      spa_model_id: input.spaModelId,
      status: input.status ?? 'pending',
      fit_notes: input.fitNotes,
      quantity_required: input.quantityRequired ?? 1,
      position: input.position,
      source: input.source ?? 'manual',
      added_by: userId,
    })
    .returning('*');

  await logAudit(
    'part_spa_compatibility',
    `${row.part_id}:${row.spa_model_id}`,
    'INSERT',
    null,
    row,
    userId
  );

  return mapCompatibilityFromDb(row);
}

export async function createBulkCompatibilities(
  partId: string,
  spaModelIds: string[],
  options: {
    status?: CompatibilityStatus;
    source?: string;
    fitNotes?: string;
  } = {},
  userId?: string
): Promise<number> {
  if (spaModelIds.length === 0) return 0;

  const insertData = spaModelIds.map((spaModelId) => ({
    part_id: partId,
    spa_model_id: spaModelId,
    status: options.status ?? 'pending',
    source: options.source ?? 'manual',
    fit_notes: options.fitNotes,
    added_by: userId,
  }));

  await db('part_spa_compatibility')
    .insert(insertData)
    .onConflict(['part_id', 'spa_model_id'])
    .ignore();

  await logAudit(
    'part_spa_compatibility',
    partId,
    'INSERT',
    null,
    { spaModelIds, status: options.status ?? 'pending' },
    userId
  );

  return spaModelIds.length;
}

export async function createMatrixCompatibilities(
  partIds: string[],
  spaModelIds: string[],
  options: {
    status?: CompatibilityStatus;
    source?: string;
  } = {},
  userId?: string
): Promise<{ created: number; skipped: number }> {
  if (partIds.length === 0 || spaModelIds.length === 0) {
    return { created: 0, skipped: 0 };
  }

  const pairs: { part_id: string; spa_model_id: string }[] = [];
  for (const partId of partIds) {
    for (const spaModelId of spaModelIds) {
      pairs.push({ part_id: partId, spa_model_id: spaModelId });
    }
  }

  const existingRows = await db('part_spa_compatibility')
    .select('part_id', 'spa_model_id')
    .whereIn(
      ['part_id', 'spa_model_id'],
      pairs.map((p) => [p.part_id, p.spa_model_id])
    );

  const existingSet = new Set(
    existingRows.map((r) => `${r.part_id}:${r.spa_model_id}`)
  );

  const toInsert = pairs.filter(
    (p) => !existingSet.has(`${p.part_id}:${p.spa_model_id}`)
  );

  if (toInsert.length > 0) {
    const insertData = toInsert.map((p) => ({
      part_id: p.part_id,
      spa_model_id: p.spa_model_id,
      status: options.status ?? 'pending',
      source: options.source ?? 'manual',
      added_by: userId,
    }));

    await db('part_spa_compatibility')
      .insert(insertData)
      .onConflict(['part_id', 'spa_model_id'])
      .ignore();

    await logAudit(
      'part_spa_compatibility',
      toInsert[0].part_id,
      'INSERT',
      null,
      { matrix: { partCount: partIds.length, spaCount: spaModelIds.length, created: toInsert.length } },
      userId
    );
  }

  return {
    created: toInsert.length,
    skipped: pairs.length - toInsert.length,
  };
}

export async function updateCompatibilityStatus(
  partId: string,
  spaModelId: string,
  status: CompatibilityStatus,
  userId?: string
): Promise<PartSpaCompatibility | null> {
  const oldRow = await db('part_spa_compatibility')
    .where({ part_id: partId, spa_model_id: spaModelId })
    .first();
  if (!oldRow) return null;

  const [row] = await db('part_spa_compatibility')
    .where({ part_id: partId, spa_model_id: spaModelId })
    .update({
      status,
      reviewed_by: userId,
      reviewed_at: db.fn.now(),
    })
    .returning('*');

  await logAudit(
    'part_spa_compatibility',
    `${partId}:${spaModelId}`,
    'UPDATE',
    oldRow,
    row,
    userId
  );

  return mapCompatibilityFromDb(row);
}

export async function deleteCompatibility(
  partId: string,
  spaModelId: string,
  userId?: string
): Promise<boolean> {
  const oldRow = await db('part_spa_compatibility')
    .where({ part_id: partId, spa_model_id: spaModelId })
    .first();
  if (!oldRow) return false;

  await db('part_spa_compatibility')
    .where({ part_id: partId, spa_model_id: spaModelId })
    .del();

  await logAudit(
    'part_spa_compatibility',
    `${partId}:${spaModelId}`,
    'DELETE',
    oldRow,
    null,
    userId
  );

  return true;
}

// =============================================================================
// Review Queue (Pending Compatibilities)
// =============================================================================

export async function getPendingCompatibilities(
  pagination?: PaginationParams
): Promise<{ items: PartSpaCompatibility[]; total: number }> {
  let query = db('part_spa_compatibility')
    .select(
      'part_spa_compatibility.*',
      'pcdb_parts.name as part_name',
      'pcdb_parts.part_number',
      'scdb_spa_models.name as spa_model_name',
      'scdb_spa_models.year as spa_year',
      'scdb_brands.name as brand_name'
    )
    .leftJoin('pcdb_parts', 'part_spa_compatibility.part_id', 'pcdb_parts.id')
    .leftJoin('scdb_spa_models', 'part_spa_compatibility.spa_model_id', 'scdb_spa_models.id')
    .leftJoin('scdb_brands', 'scdb_spa_models.brand_id', 'scdb_brands.id')
    .where('part_spa_compatibility.status', 'pending');

  const countResult = await db('part_spa_compatibility')
    .where('status', 'pending')
    .count('* as count')
    .first();
  const total = parseInt((countResult?.count as string) ?? '0', 10);

  query = query.orderBy('part_spa_compatibility.added_at', 'desc');

  if (pagination?.page && pagination?.pageSize) {
    const offset = (pagination.page - 1) * pagination.pageSize;
    query = query.offset(offset).limit(pagination.pageSize);
  }

  const rows = await query;
  return {
    items: rows.map(mapCompatibilityFromDb),
    total,
  };
}

// =============================================================================
// Compatibility Groups (Comps)
// =============================================================================

export async function listComps(
  includeDeleted = false,
  pagination?: PaginationParams
): Promise<{ comps: CompatibilityGroup[]; total: number }> {
  let query = db('compatibility_groups')
    .select(
      'compatibility_groups.*',
      db.raw('(SELECT COUNT(*) FROM comp_spas WHERE comp_spas.comp_id = compatibility_groups.id) as spa_count'),
      'pcdb_categories.name as source_category_name'
    )
    .leftJoin('pcdb_categories', 'compatibility_groups.source_category_id', 'pcdb_categories.id');

  if (!includeDeleted) {
    query = query.whereNull('compatibility_groups.deleted_at');
  }

  const countQuery = includeDeleted
    ? db('compatibility_groups')
    : db('compatibility_groups').whereNull('deleted_at');
  const countResult = await countQuery.count('* as count').first();
  const total = parseInt((countResult?.count as string) ?? '0', 10);

  const sortBy = pagination?.sortBy || 'compatibility_groups.id';
  const sortOrder = pagination?.sortOrder || 'asc';
  query = query.orderBy(sortBy, sortOrder);

  if (pagination?.page && pagination?.pageSize) {
    const offset = (pagination.page - 1) * pagination.pageSize;
    query = query.offset(offset).limit(pagination.pageSize);
  }

  const rows = await query;
  return {
    comps: rows.map(mapCompFromDb),
    total,
  };
}

export async function getCompById(id: string): Promise<CompatibilityGroup | null> {
  const row = await db('compatibility_groups')
    .select(
      'compatibility_groups.*',
      db.raw('(SELECT COUNT(*) FROM comp_spas WHERE comp_spas.comp_id = compatibility_groups.id) as spa_count'),
      'pcdb_categories.name as source_category_name'
    )
    .leftJoin('pcdb_categories', 'compatibility_groups.source_category_id', 'pcdb_categories.id')
    .where('compatibility_groups.id', id)
    .whereNull('compatibility_groups.deleted_at')
    .first();

  return row ? mapCompFromDb(row) : null;
}

export async function createComp(input: CreateCompInput, userId?: string): Promise<CompatibilityGroup> {
  const [row] = await db('compatibility_groups')
    .insert({
      id: input.id,
      name: input.name,
      description: input.description,
      auto_generated: false,
      created_by: userId,
    })
    .returning('*');

  // Add spa memberships if provided
  if (input.spaModelIds && input.spaModelIds.length > 0) {
    const compSpas = input.spaModelIds.map((spaId) => ({
      comp_id: row.id,
      spa_model_id: spaId,
    }));
    await db('comp_spas').insert(compSpas);
  }

  await logAudit('compatibility_groups', row.id, 'INSERT', null, row, userId);

  return (await getCompById(row.id))!;
}

export async function updateComp(
  id: string,
  input: UpdateCompInput,
  userId?: string
): Promise<CompatibilityGroup | null> {
  const oldRow = await db('compatibility_groups').where({ id }).first();
  if (!oldRow || oldRow.deleted_at) return null;

  const updateData: Record<string, unknown> = { updated_at: db.fn.now() };
  if (input.name !== undefined) updateData.name = input.name;
  if (input.description !== undefined) updateData.description = input.description;

  const [row] = await db('compatibility_groups').where({ id }).update(updateData).returning('*');

  await logAudit('compatibility_groups', row.id, 'UPDATE', oldRow, row, userId);
  return getCompById(row.id);
}

export async function deleteComp(id: string, userId?: string): Promise<boolean> {
  const oldRow = await db('compatibility_groups').where({ id }).first();
  if (!oldRow || oldRow.deleted_at) return false;

  await db('compatibility_groups').where({ id }).update({ deleted_at: db.fn.now() });
  await logAudit('compatibility_groups', id, 'DELETE', oldRow, null, userId);
  return true;
}

// =============================================================================
// Comp Spa Membership
// =============================================================================

export async function getSpasInComp(compId: string): Promise<CompSpa[]> {
  const rows = await db('comp_spas')
    .select(
      'comp_spas.*',
      'scdb_spa_models.name as spa_model_name',
      'scdb_spa_models.year as spa_year',
      'scdb_brands.name as brand_name',
      'scdb_model_lines.name as model_line_name'
    )
    .leftJoin('scdb_spa_models', 'comp_spas.spa_model_id', 'scdb_spa_models.id')
    .leftJoin('scdb_brands', 'scdb_spa_models.brand_id', 'scdb_brands.id')
    .leftJoin('scdb_model_lines', 'scdb_spa_models.model_line_id', 'scdb_model_lines.id')
    .where('comp_spas.comp_id', compId)
    .orderBy('scdb_brands.name')
    .orderBy('scdb_spa_models.name')
    .orderBy('scdb_spa_models.year', 'desc');

  return rows.map((row) => ({
    compId: row.comp_id,
    spaModelId: row.spa_model_id,
    addedAt: row.added_at,
    spaModelName: row.spa_model_name,
    spaYear: row.spa_year,
    brandName: row.brand_name,
    modelLineName: row.model_line_name,
  }));
}

export async function addSpasToComp(
  compId: string,
  spaModelIds: string[],
  userId?: string
): Promise<number> {
  if (spaModelIds.length === 0) return 0;

  const insertData = spaModelIds.map((spaId) => ({
    comp_id: compId,
    spa_model_id: spaId,
  }));

  await db('comp_spas').insert(insertData).onConflict(['comp_id', 'spa_model_id']).ignore();

  await db('compatibility_groups').where({ id: compId }).update({ updated_at: db.fn.now() });

  await logAudit(
    'comp_spas',
    compId,
    'INSERT',
    null,
    { compId, spaModelIds },
    userId
  );

  return spaModelIds.length;
}

export async function removeSpasFromComp(
  compId: string,
  spaModelIds: string[],
  userId?: string
): Promise<number> {
  if (spaModelIds.length === 0) return 0;

  const deleted = await db('comp_spas')
    .where('comp_id', compId)
    .whereIn('spa_model_id', spaModelIds)
    .del();

  await db('compatibility_groups').where({ id: compId }).update({ updated_at: db.fn.now() });

  await logAudit(
    'comp_spas',
    compId,
    'DELETE',
    { compId, spaModelIds },
    null,
    userId
  );

  return deleted;
}

export async function setCompSpas(
  compId: string,
  spaModelIds: string[],
  userId?: string
): Promise<void> {
  await db('comp_spas').where('comp_id', compId).del();

  if (spaModelIds.length > 0) {
    const insertData = spaModelIds.map((spaId) => ({
      comp_id: compId,
      spa_model_id: spaId,
    }));
    await db('comp_spas').insert(insertData);
  }

  await db('compatibility_groups').where({ id: compId }).update({ updated_at: db.fn.now() });

  await logAudit(
    'comp_spas',
    compId,
    'UPDATE',
    null,
    { compId, spaModelIds },
    userId
  );
}

// =============================================================================
// Computed Part Membership (Dynamic - NOT stored)
// =============================================================================

export async function getPartsForComp(compId: string): Promise<string[]> {
  // Parts that are compatible with ALL spas in the Comp
  const compSpas = await db('comp_spas').select('spa_model_id').where('comp_id', compId);
  if (compSpas.length === 0) return [];

  const spaIds = compSpas.map((cs) => cs.spa_model_id);

  // Find parts where the count of confirmed compatibilities equals the number of spas in the Comp
  const rows = await db('part_spa_compatibility')
    .select('part_id')
    .whereIn('spa_model_id', spaIds)
    .where('status', 'confirmed')
    .groupBy('part_id')
    .havingRaw('COUNT(DISTINCT spa_model_id) = ?', [spaIds.length]);

  return rows.map((r) => r.part_id);
}

// =============================================================================
// Near-Match Suggestions
// =============================================================================

export async function findNearMatchComps(
  spaModelIds: string[],
  categoryId?: string,
  threshold = 0.5
): Promise<CompNearMatch[]> {
  if (spaModelIds.length === 0) return [];

  // Get all Comps
  let compsQuery = db('compatibility_groups')
    .select('compatibility_groups.*')
    .whereNull('compatibility_groups.deleted_at');

  if (categoryId) {
    compsQuery = compsQuery.where('compatibility_groups.source_category_id', categoryId);
  }

  const comps = await compsQuery;
  const results: CompNearMatch[] = [];

  for (const comp of comps) {
    const compSpas = await db('comp_spas').select('spa_model_id').where('comp_id', comp.id);
    const compSpaIds = new Set(compSpas.map((cs) => cs.spa_model_id));

    if (compSpaIds.size === 0) continue;

    // Count matching spas
    const matchingCount = spaModelIds.filter((id) => compSpaIds.has(id)).length;
    const matchPercentage = matchingCount / compSpaIds.size;

    if (matchPercentage >= threshold) {
      results.push({
        comp: mapCompFromDb({ ...comp, spa_count: String(compSpaIds.size) }),
        matchingSpas: matchingCount,
        totalCompSpas: compSpaIds.size,
        matchPercentage,
      });
    }
  }

  // Sort by match percentage descending
  results.sort((a, b) => b.matchPercentage - a.matchPercentage);

  return results;
}

// =============================================================================
// Auto-Generation of Comps
// =============================================================================

export async function generateCompIdSuggestion(
  brandAbbrev: string,
  categoryAbbrev: string
): Promise<string> {
  // Find highest existing number for this pattern
  const pattern = `COMP-${brandAbbrev.toUpperCase()}-${categoryAbbrev.toUpperCase()}-%`;
  const existing = await db('compatibility_groups')
    .select('id')
    .whereRaw('id LIKE ?', [pattern])
    .orderBy('id', 'desc')
    .limit(1);

  if (existing.length === 0) {
    return `COMP-${brandAbbrev.toUpperCase()}-${categoryAbbrev.toUpperCase()}-001`;
  }

  const lastId = existing[0].id;
  const numPart = lastId.split('-').pop();
  const nextNum = parseInt(numPart!, 10) + 1;
  return `COMP-${brandAbbrev.toUpperCase()}-${categoryAbbrev.toUpperCase()}-${String(nextNum).padStart(3, '0')}`;
}

export async function shouldAutoGenerateComp(
  partId: string,
  spaModelIds: string[],
  categoryId: string
): Promise<{ shouldGenerate: boolean; existingComp?: CompatibilityGroup }> {
  if (spaModelIds.length < 2) {
    return { shouldGenerate: false };
  }

  // Check if there's an existing Comp with exact same spas in same category
  const comps = await db('compatibility_groups')
    .select('compatibility_groups.*')
    .where('source_category_id', categoryId)
    .whereNull('deleted_at');

  for (const comp of comps) {
    const compSpas = await db('comp_spas').select('spa_model_id').where('comp_id', comp.id);
    const compSpaIds = compSpas.map((cs) => cs.spa_model_id).sort();

    if (
      compSpaIds.length === spaModelIds.length &&
      compSpaIds.every((id, i) => id === [...spaModelIds].sort()[i])
    ) {
      return { shouldGenerate: false, existingComp: mapCompFromDb(comp) };
    }
  }

  // Check if 2+ parts share these exact spas in this category
  const partsWithSameCompat = await db('part_spa_compatibility')
    .select('part_id')
    .leftJoin('pcdb_parts', 'part_spa_compatibility.part_id', 'pcdb_parts.id')
    .whereIn('spa_model_id', spaModelIds)
    .where('pcdb_parts.category_id', categoryId)
    .where('status', 'confirmed')
    .groupBy('part_id')
    .havingRaw('COUNT(DISTINCT spa_model_id) = ?', [spaModelIds.length]);

  return { shouldGenerate: partsWithSameCompat.length >= 2 };
}

// =============================================================================
// Assign Part to Comp
// =============================================================================

export async function assignPartToCompSpas(
  partId: string,
  compId: string,
  options: {
    status?: CompatibilityStatus;
    userId?: string;
  } = {}
): Promise<number> {
  const compSpas = await db('comp_spas').select('spa_model_id').where('comp_id', compId);
  const spaModelIds = compSpas.map((cs) => cs.spa_model_id);

  return createBulkCompatibilities(
    partId,
    spaModelIds,
    {
      status: options.status ?? 'pending',
      source: 'comp_assignment',
    },
    options.userId
  );
}

// =============================================================================
// Stats
// =============================================================================

export async function getCompatibilityStats(): Promise<{
  totalCompatibilities: number;
  pendingCount: number;
  confirmedCount: number;
  totalComps: number;
  autoGeneratedComps: number;
}> {
  const [compatStats] = await db('part_spa_compatibility')
    .select(
      db.raw('COUNT(*) as total'),
      db.raw("COUNT(*) FILTER (WHERE status = 'pending') as pending"),
      db.raw("COUNT(*) FILTER (WHERE status = 'confirmed') as confirmed")
    );

  const [compStats] = await db('compatibility_groups')
    .select(
      db.raw('COUNT(*) as total'),
      db.raw('COUNT(*) FILTER (WHERE auto_generated = true) as auto_generated')
    )
    .whereNull('deleted_at');

  return {
    totalCompatibilities: parseInt(compatStats.total, 10),
    pendingCount: parseInt(compatStats.pending, 10),
    confirmedCount: parseInt(compatStats.confirmed, 10),
    totalComps: parseInt(compStats.total, 10),
    autoGeneratedComps: parseInt(compStats.auto_generated, 10),
  };
}
