'use client';

import React, { useState, useEffect } from 'react';
import { Modal } from '../ui/Modal';
import { Badge } from '../ui/Badge';
import { Button } from '../ui/Button';

interface CompSpa {
  spaModelId: string;
  spaModelName?: string;
  spaYear?: number;
  brandName?: string;
  modelLineName?: string;
}

interface CompQuickviewProps {
  compId: string | null;
  isOpen: boolean;
  onClose: () => void;
  onSelectAll?: (spaIds: string[]) => void;
}

export function CompQuickview({ compId, isOpen, onClose, onSelectAll }: CompQuickviewProps) {
  const [comp, setComp] = useState<{
    id: string;
    name: string | null;
    description: string | null;
    autoGenerated: boolean;
    spaCount?: number;
  } | null>(null);
  const [spas, setSpas] = useState<CompSpa[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!compId || !isOpen) return;

    const fetchCompDetails = async () => {
      setLoading(true);
      try {
        const [compRes, spasRes] = await Promise.all([
          fetch(`/api/dashboard/super-admin/comps/${compId}`),
          fetch(`/api/dashboard/super-admin/comps/${compId}/spas`),
        ]);

        const compData = await compRes.json();
        const spasData = await spasRes.json();

        if (compData.success) {
          setComp(compData.data);
        }
        if (spasData.success) {
          setSpas(spasData.data || []);
        }
      } catch (err) {
        console.error('Error fetching comp details:', err);
      } finally {
        setLoading(false);
      }
    };

    fetchCompDetails();
  }, [compId, isOpen]);

  const handleSelectAll = () => {
    if (onSelectAll && spas.length > 0) {
      onSelectAll(spas.map((s) => s.spaModelId));
      onClose();
    }
  };

  // Group spas by brand
  const spasByBrand = spas.reduce<Record<string, CompSpa[]>>((acc, spa) => {
    const brand = spa.brandName || 'Unknown';
    if (!acc[brand]) acc[brand] = [];
    acc[brand].push(spa);
    return acc;
  }, {});

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={comp?.id || 'Loading...'}
      size="lg"
      footer={
        onSelectAll && (
          <div className="flex justify-end gap-3">
            <Button variant="secondary" onClick={onClose}>
              Cancel
            </Button>
            <Button onClick={handleSelectAll} disabled={spas.length === 0}>
              Select All {spas.length} Spas
            </Button>
          </div>
        )
      }
    >
      {loading ? (
        <div className="flex items-center justify-center py-8">
          <svg className="animate-spin h-6 w-6 text-blue-600" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
        </div>
      ) : comp ? (
        <div>
          <div className="flex items-center gap-3 mb-4">
            {comp.name && <span className="text-gray-600">{comp.name}</span>}
            {comp.autoGenerated && (
              <Badge variant="info" size="sm">Auto-generated</Badge>
            )}
          </div>

          {comp.description && (
            <p className="text-sm text-gray-600 mb-4">{comp.description}</p>
          )}

          <div className="mb-4">
            <h4 className="text-sm font-medium text-gray-900 mb-2">
              Spa Models ({spas.length})
            </h4>
            <div className="border border-gray-200 rounded-lg overflow-hidden max-h-[400px] overflow-y-auto">
              {Object.entries(spasByBrand).map(([brand, brandSpas]) => (
                <div key={brand} className="border-b border-gray-200 last:border-b-0">
                  <div className="px-4 py-2 bg-gray-50 text-sm font-medium text-gray-700">
                    {brand} ({brandSpas.length})
                  </div>
                  <div className="divide-y divide-gray-100">
                    {brandSpas.map((spa) => (
                      <div key={spa.spaModelId} className="px-4 py-2 text-sm">
                        <span className="text-gray-900">{spa.spaModelName}</span>
                        <span className="text-gray-500 ml-2">{spa.spaYear}</span>
                        {spa.modelLineName && (
                          <span className="text-gray-400 ml-2">({spa.modelLineName})</span>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      ) : (
        <div className="text-center py-8 text-gray-500">Comp not found</div>
      )}
    </Modal>
  );
}
